# Generated by Django 6.0.2 on 2026-03-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='image',
        ),
        migrations.AddField(
            model_name='slidegroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slides/'),
        ),
    ]
